### ISSUE TITLE
Push 1.8.0 to Docker hub

### ISSUE THREAD

**Issue by tinoadams** [runtimeco/newt-docker#14]
Hi mate, are you planning on pushing a 1.8.0 image to  the Docker hub? Many thanks.

**Comment by utzig** [comment]
> Hi mate, are you planning on pushing a 1.8.0 image to the Docker hub? Many thanks.

Done.

**Comment by utzig** [comment]
I am closing this, feel free to reopen if you find any issues.

**Comment by tinoadams** [comment]
All good. Thank you very much.
