### ISSUE TITLE
make toolchain-image error

### ISSUE THREAD

**Issue by melnarte** [runtimeco/newt-docker#17]
`
PS Y:\Docker\newt-docker> make toolchain-image
curl -X POST -d "accept_license_agreement=accepted" -o JLink_Linux_V648_x86_64.deb https://www.segger.com/downloads/jlink/JLink_Linux_V648_x86_64.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 29.1M  100 29.1M  100    33  1758k      1  0:00:33  0:00:17  0:00:16 1917k
shasum -c JLink_Linux_V648_x86_64.deb.sha256
process_begin: CreateProcess(NULL, shasum -c JLink_Linux_V648_x86_64.deb.sha256, ...) failed.
make (e=2): The system cannot find the file specified.
make: *** [Makefile:22: JLink_Linux_V648_x86_64.deb] Error 2
`

**Comment by utzig** [comment]
Are you trying to update the docker image? Otherwise you could just `docker pull mynewt/newt` to install the last published, although it is still `1.8.0`, so it also needs to be updated.

**Comment by melnarte** [comment]
I am following a tutorial and it is written 'To build the newt docker image: make toolchain-image. So this command fails. I'll try to follow your advice and use the only latest image. Thank you.
