### ISSUE TITLE
Container comes with out-of-date OpenOCD

### ISSUE THREAD

**Issue by bdebyl** [runtimeco/newt-docker#4]
The docker container from `:latest`, or older, seems to contain an out of date (`0.9.x`) version of OpenOCD when the [Documentation](https://mynewt.apache.org/develop/get_started/native_install/cross_tools.html#installing-openocd-on-linux) expressly states to use `0.10.0`. It seems as though the base image doesn't seem to have the latest version of `openocd` even when running an `apt-get update` from inside a `docker run -it bash` of the newt image: https://github.com/runtimeco/newt-docker/blob/master/Dockerfile.toolchain#L18

```
 docker run -it mynewt/newt:latest bash
root@d314c2cb8c7c:/# apt-cache policy openocd
openocd:
  Installed: 0.9.0-1build1
  Candidate: 0.9.0-1build1
  Version table:
 *** 0.9.0-1build1 100
        100 /var/lib/dpkg/status
root@d314c2cb8c7c:/# openocd --version
Open On-Chip Debugger 0.9.0 (2015-09-02-10:42)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
root@d314c2cb8c7c:/# exit
```

**Comment by utzig** [comment]
Fixed by #6
